name: run-haskell-module
version: '0.0.2'
synopsis: Running newly generated Haskell source module.
description: ! 'To make sure freshly generated code runs,

  we need to make it run in Stack/Cabal/GHC environment.'
category: Data, Tools
author:
- Michal J. Gajda
- Dmitrii Krylov
maintainer:
  - simons@cryp.to
  - mjgajda@gmail.com
copyright: Copyright by Michal J. Gajda '2014-'2020
license: BSD3
git: https://gitlab.com/migamake/json-autotype.git
tested-with: GHC==8.4.4 GHC==8.6.5 GHC==8.8.2 GHC==8.10.1
extra-source-files:
- README.md
- changelog.md
dependencies:
- base >=4.3 && <5
- data-default >=0.7 && <0.8
- filepath >=1.3 && <1.5
- process >=1.1 && <1.7
library:
  source-dirs: src
  exposed-modules:
  - Language.Haskell.RunHaskellModule
stability: beta
